/**
 * MANTUL - Optimized Aurealisa.com
 * Includes: TOC, Smooth Zoom, Dark Mode, Lazyload (Observer), Turbo Hotwire
 */

// 1. KONFIGURASI DAFTAR ISI (TOC)
var toc_options={target:["h2","h3","h4"],autoNumber:!0,condTargetCount:2,insertPosition:"firstHeadBefore",showToc:!0,postBodySelector:".post-content"};
var scrollHandler=null; const imgReg=/\b(http(?:s)?:\/\/\S+(?:png|jpe?g|gif|bmp|svg|webp|tif)\S*)\b/gi,ytbReg=/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)([\w-]{11})(?:\S+)?/gi;

// 2. FUNGSI DAFTAR ISI (TOC)
function initTOC(){var e=document.querySelector(toc_options.postBodySelector);if(e){var t,o,a,n,l,r,i=(t=toc_options,o=e,a=t.target.map(e=>e.toLowerCase()),n=o.querySelectorAll(a.join(", ")),l={children:[]},r=[l],n.forEach(function(e){var t,o=a.indexOf(e.tagName.toLowerCase()),n=e.innerText.trim(),l=e.id||(t=n).toString().toLowerCase().replace(/\s+/g,"-").replace(/[^\w\-]+/g,"").replace(/\-\-+/g,"-").replace(/^-+/,"").replace(/-+$/,"");l||(l="section-"+Math.floor(1e3*Math.random())),e.id=l;for(var i={text:n,id:l,children:[],level:o};r.length>o+1;)r.pop();r[r.length-1]&&(r[r.length-1].children.push(i),r.push(i))}),l);if(i.children.length>=toc_options.condTargetCount){var s,c,d,m,p,u,g=document.querySelector(".b-toc-container");g&&g.remove();var h=(s=i,c=document.createElement("div"),c.className="b-toc-container card mb-4 shadow-sm",c.id="main-toc-area",d=document.createElement("div"),d.className="toc-header d-flex justify-content-between align-items-center p-3",d.innerHTML='<span class="fw-bold">Daftar Isi</span>',m=document.createElement("button"),m.className="btn btn-sm btn-outline-secondary",m.innerText=toc_options.showToc?"Sembunyikan":"Tampilkan",d.appendChild(m),p=document.createElement("div"),p.className="toc-body p-3 pt-0",toc_options.showToc||(p.style.display="none"),u=function e(t,o,a){if(0===t.length)return null;var n=document.createElement("ul");return n.className=o?"toc-list toc-root":"toc-list toc-child",t.forEach(function(t,o){var l=a?a+(o+1):o+1,r=document.createElement("li");r.className="toc-item";var i=document.createElement("a");i.href="#"+t.id,i.className="toc-link";var s=toc_options.autoNumber?'<span class="toc-number">'+l+".</span> ":"";i.innerHTML=s+'<span class="toc-text">'+t.text+"</span>",i.addEventListener("click",function(e){e.preventDefault();var o=document.getElementById(t.id);if(o){var a=c.getBoundingClientRect().top+window.pageYOffset-100,n=o.getBoundingClientRect().top+window.pageYOffset-90;window.scrollTo({top:n,behavior:"smooth"}),history.pushState({isHeading:!0,tocPos:a},null,"#"+t.id)}}),r.appendChild(i);var d=e(t.children,!1,l+".");d&&r.appendChild(d),n.appendChild(r)}),n}(s.children,!0,""),u&&p.appendChild(u),m.onclick=function(){var e="none"===p.style.display;p.style.display=e?"block":"none",m.innerText=e?"Sembunyikan":"Tampilkan"},c.appendChild(d),c.appendChild(p),setTimeout(function e(){var t=c.getBoundingClientRect().top+window.pageYOffset-100;history.replaceState({tocPos:t},"")},500),c),f=e.querySelector(toc_options.target[0]);f&&f.parentNode.insertBefore(h,f)}}}

// 3. FUNGSI IMAGE ZOOM & LIGHTBOX
function initSmoothZoom(){let e=document.querySelector(".zoom-overlay"),t=0,o=[];if(!e){(e=document.createElement("div")).className="zoom-overlay",e.innerHTML=` <div class="zoom-bg"></div> <div class="zoom-counter">0 / 0</div> <button class="zoom-prev" aria-label="Previous">&lsaquo;</button> <img class="zoom-img" src="" alt="Loading..."/> <button class="zoom-next" aria-label="Next">&rsaquo;</button> `,document.body.appendChild(e);let a=()=>{e.classList.remove("active"),setTimeout(()=>{e.style.display="none"},300)};e.querySelector(".zoom-bg").onclick=a,e.querySelector(".zoom-prev").onclick=e=>{e.stopPropagation(),s(-1)},e.querySelector(".zoom-next").onclick=e=>{e.stopPropagation(),s(1)},document.addEventListener("keydown",t=>{e.classList.contains("active")&&("Escape"===t.key&&a(),"ArrowLeft"===t.key&&s(-1),"ArrowRight"===t.key&&s(1))})}let n=e.querySelector(".zoom-img"),l=e.querySelector(".zoom-counter"),r=document.querySelectorAll(".separator img, .tr-caption-container img, .post-content img:not(.no-zoom), .img-comment");o=Array.from(r);let i=e=>{let t=o[e];if(!t)return;let a=t.src;(a.includes("blogger.googleusercontent.com")||a.includes("bp.blogspot.com"))&&(a=a.replace(/\/[swh]\d+.*\//,"/s0-rw/").replace(/=[swh]\d+.*/,"=s0-rw")),n.style.opacity="0",setTimeout(()=>{n.src=a,n.setAttribute("alt",t.getAttribute("alt")||"Image"),l.innerText=`${e+1} / ${o.length}`,n.style.opacity="1"},150)},s=e=>{i(t=(t+e+o.length)%o.length)};o.forEach((o,a)=>{o.classList.add("zoomable"),o.onclick=o=>{o.preventDefault(),o.stopPropagation(),i(t=a),e.style.display="flex",setTimeout(()=>e.classList.add("active"),10)};let n=o.closest("a");n&&(n.onclick=e=>e.preventDefault())})}

// 4. PROSES KOMENTAR & YOUTUBE
function processComments(){document.querySelectorAll(".commentBody").forEach(e=>{let t=e.innerHTML;imgReg.test(t)&&(t=t.replace(imgReg,e=>`<img alt='Gambar' class='lazy img-comment' data-src='${e}' src='data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='/>`)),ytbReg.test(t)&&(t=t.replace(ytbReg,e=>{let t=e.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)([\w-]{11})/i);return t&&t[1]?`<div class='lazy-youtube' data-video-id='${t[1]}'><div class='lazy-youtube-play'></div></div>`:e})),e.innerHTML=t}),initYoutubeClick(),"function"==typeof lazyLoadInit&&lazyLoadInit()}
function initYoutubeClick(){document.querySelectorAll(".lazy-youtube").forEach(e=>{if(e.dataset.initialized)return;e.dataset.initialized="true";let t=e.querySelector(".lazy-youtube-play");t&&(t.onclick=function(){let t=e.dataset.videoId;t&&(e.innerHTML=`<iframe src="https://www.youtube.com/embed/${t}?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`)})})}

// 5. UTILITY: TOAST, COPY, & THEME
function showToast(e){let t=document.getElementById("main-toast");if(!t)return;let o=t.querySelector(".toast-body");if(o&&(o.innerHTML=e),"undefined"!=typeof bootstrap){let a=new bootstrap.Toast(t);a.show()}}
function copyThis(e){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(e).then(()=>{showToast("Success Copy")});else{let t=document.createElement("textarea");t.value=e,t.style.position="fixed",t.style.left="-999999px",t.style.top="-999999px",document.body.appendChild(t),t.focus(),t.select();try{document.execCommand("copy"),showToast("Success Copy")}catch(o){console.error("Gagal copy: ",o)}t.remove()}}
function updateAddressBarColor(){let e=document.querySelector("meta[name='theme-color']");if(!e)return;let t=document.body.classList.contains("dark-mode");e.setAttribute("content",t?"#15202b":"#0078d4")}

// 6. TIME AGO (WAKTU KE KATA)
function waktuKeKata(e,t){t=t||{postfixes:{"<":" yang lalu"},1e3:{singular:"beberapa detik",plural:"beberapa detik"},6e4:{singular:"sekitar semenit",plural:"# menit"},36e5:{singular:"sekitar sejam",plural:"# jam"},864e5:{singular:"sehari",plural:"# hari"},2592e6:{singular:"sebulan",plural:"# bulan"},3154e7:{singular:"setahun",plural:"# tahun"}};let o=[1e3,6e4,36e5,864e5,2592e6,3154e7],a=Date.parse(e.replace(/\-00:?00$/,""));if(!a||!Date.now)return null;let n=Math.abs(a-Date.now()),l=t.postfixes["<"],r=o[0];for(let i=1;i<o.length;i++)n>o[i]&&(r=o[i]);let s=Math.round(n/r);return t[r][s>1?"plural":"singular"].replace("#",s)+l}
function prosesSemuaTagTime(){let e=document.getElementsByTagName("time");for(let t=0;t<e.length;t++){let o=e[t],a=waktuKeKata(o.getAttribute("datetime")||o.textContent);a&&(o.textContent=a)}}

// 7. NAVIGASI UTAMA & DARK MODE
function mainNav(){let e=document.querySelectorAll("#main-nav div.nav-link"),t={content:document.getElementById("main-content"),categories:document.getElementById("main-categories"),archive:document.getElementById("main-archive"),sidebar:document.getElementById("main-sidebar"),header:document.getElementById("widget-main-header"),pinned:document.getElementById("widget-main-pinned")};e.forEach(o=>{o.onclick=function(o){o.preventDefault();let a=this.getAttribute("data-nav");e.forEach(e=>e.classList.remove("active")),this.classList.add("active"),Object.values(t).forEach(e=>{e&&e.classList.add("d-none")});let n=document.getElementById("main-"+a);n&&n.classList.remove("d-none")}}),document.querySelectorAll(".back-to-content").forEach(o=>{o.onclick=()=>{[t.categories,t.archive,t.sidebar].forEach(e=>e&&e.classList.add("d-none")),e.forEach(e=>e.classList.remove("active")),[t.header,t.pinned,t.content].forEach(e=>e&&e.classList.remove("d-none"))}})}
function darkMode(){let e=document.querySelectorAll(".dark-mode");if(0===e.length)return;let t=t=>{t?(document.body.classList.add("dark-mode"),document.querySelectorAll("#main-header, #main-nav").forEach(e=>{e.classList.remove("navbar-light","bg-white"),e.classList.add("navbar-dark","bg-dark")})):(document.body.classList.remove("dark-mode"),document.querySelectorAll("#main-header, #main-nav").forEach(e=>{e.classList.remove("navbar-dark","bg-dark"),e.classList.add("navbar-light","bg-white")})),e.forEach(e=>{let o=e.querySelector("i");o&&(t?o.classList.replace("bi-moon","bi-brightness-high"):o.classList.replace("bi-brightness-high","bi-moon"))}),updateAddressBarColor()};t("true"===localStorage.getItem("dark")),e.forEach(e=>{e.onclick=e=>{e.preventDefault();let o="true"!==localStorage.getItem("dark");localStorage.setItem("dark",o),t(o)}})}

// 8. PAGINATION & RELATED POSTS
function postPaginationMultiple(){let e=document.getElementById("postPaginationMultiple");if(!e)return;scrollHandler&&(window.removeEventListener("scroll",scrollHandler),scrollHandler=null);let t=!1;e.onclick=function(o){let a=o.target.closest("a.pagination-link");if(a&&!t){o.preventDefault(),t=!0;let n=e.innerHTML;e.innerHTML='<div class="text-center py-3"><div class="spinner-border text-primary" role="status"></div></div>',fetch(a.href).then(e=>e.text()).then(o=>{let a=new DOMParser().parseFromString(o,"text/html"),n=a.getElementById("postIndex"),l=a.getElementById("postPaginationMultiple");if(n){let r=document.getElementById("postIndex");r&&(r.insertAdjacentHTML("beforeend",n.innerHTML),prosesSemuaTagTime(),lazyLoadInit(),initSmoothZoom())}l&&l.querySelector("a.pagination-link")?(e.innerHTML=l.innerHTML,t=!1):e.innerHTML='<div class="text-center text-success fw-bold fs-3"><i class="bi bi-check-circle"></i></div>'}).catch(()=>{e.innerHTML=n,t=!1})}}}
function relatedPost(){let e=document.getElementById("relatedPost");if(!e||e.dataset.loaded)return;e.dataset.loaded="true";let t=e.dataset.limit||4,l=e.dataset.id,i=e.dataset.labels;if(!i)return e.remove();let s='<div class="list-group rounded-0 w-auto px-3 px-md-4 py-2"><strong class="fs-4 mb-2">Similar Topic</strong>';for(let a=0;a<t;a++)s+=` <div class="post-card list-group-item d-flex align-items-center gap-3 p-0 loading"> <div class="post-image skeleton" style="width:100px; height:100px;"></div> <div class="d-flex flex-column py-2 w-100"> <div class="skeleton-line" style="width: 85%; height: 18px; margin-bottom: 8px;"></div> <div class="skeleton-line" style="width: 40%; height: 12px;"></div> </div> </div>`;e.innerHTML=s+"</div>";let d=i.split(","),o=[];Promise.all(d.map(e=>fetch(`/feeds/posts/default/-/${e.trim()}?alt=json&max-results=5`).then(e=>e.json()).then(e=>{e.feed&&e.feed.entry&&o.push(...e.feed.entry)}).catch(()=>{}))).then(()=>{let i=o.map(e=>{let t=e.id.$t.split("post-")[1],l=e.link.find(e=>"alternate"===e.rel).href,i="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj3Ia32aeortEtnG6libJiXjj6It8o5ikSjQEaPSvLK09ORfnWovo0FQX25VeAB-cSySlozaol3LZ-9C7BVpfeMMcxtEE7SxW-BCLVX4wwywof7kiBCp8nsHbre7ScleqehuZzY0G17M1mBV1H-KzYd1QW098SZzEAHE0GecLG5u2ULhnEYtKTsWUMp/w300/no-image.jpg";e.media$thumbnail&&(i=e.media$thumbnail.url.replace(/\/s[0-9]+.*?\//,"/w300-h300-p-k-no-nu/"));let s=e.published.$t;return{id:t,title:e.title.$t,url:l,image:"data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",realImage:i,date:s}}).filter(e=>e.id!==l);if((i=Array.from(new Map(i.map(e=>[e.id,e])).values()).sort(()=>Math.random()-.5)).length){let s='<div class="list-group rounded-0 w-auto px-3 px-md-4 py-2"><strong class="fs-4 mb-2">Similar Topic</strong>';i.slice(0,t).forEach(e=>{s+=`<a class="post-card list-group-item list-group-item-action d-flex align-items-center gap-3 p-0" href="${e.url}"> <div class='post-image loading'> <img alt='${e.title}' class='lazy' data-src='${e.realImage}' src='${e.image}' height='100' width='100' style='object-fit:cover;'/> </div> <div class="d-flex flex-column py-2"> <h2 class="post-title m-auto py-2">${e.title}</h2> <small class="post-date"><time datetime="${e.date}">${e.date}</time></small> </div> </a>`}),e.innerHTML=s+"</div>",prosesSemuaTagTime(),lazyLoadInit()}else e.remove()})}

// 9. BLOGGER COMMENT LOAD
function postComment(){let e=document.getElementById("comment-editor");if(!e||e.dataset.loaded)return;e.dataset.loaded="true";window.BLOG_CMT_createIframe=void 0;let t=e.getAttribute("data-src"),o=document.getElementById("blogger-comment-js");o&&o.remove();let a=document.createElement("script");a.id="blogger-comment-js",a.src="https://www.blogger.com/static/v1/jsbin/3262169375-comment_from_post_iframe.js",a.onload=()=>{window.BLOG_CMT_createIframe&&window.BLOG_CMT_createIframe("https://www.blogger.com/rpc_relay.html")},document.head.appendChild(a),document.querySelectorAll(".commentActionButton").forEach(o=>{o.onclick=function(){let o=this.dataset.id,a="addNewComment"!==o?document.getElementById("form-container-"+o):document.getElementById("commentFormWrapper"),n=document.getElementById("commentForm");if(t){let l=t.split("#");e.src="addNewComment"!==o?`${l[0]}&parentID=${o}#${l[1]}`:`${l[0]}#${l[1]}`}a&&n&&(a.appendChild(n),n.style.display="block")}})}

// 10. LAZYLOAD & OTHERS (OPTIMIZED DENGAN INTERSECTION OBSERVER)
function adsMove(){let e=document.querySelectorAll(".post-content p"),t=document.querySelector(".ads-move-to-post-middle");t&&e.length>2&&e[Math.floor(e.length/2)].after(t);let o=document.querySelector(".ads-move-to-post-bottom"),a=document.querySelector(".ads-target-post-bottom");o&&a&&a.appendChild(o)}
function backToTop(){let e=document.getElementById("btn-back-to-top");e&&(window.addEventListener("scroll",()=>{e.style.display=window.scrollY>300?"block":"none"},{passive:!0}),e.onclick=()=>window.scrollTo({top:0,behavior:"smooth"}))}
function lazyLoadInit(){let e=document.querySelectorAll("img.lazy");if("IntersectionObserver"in window){let t=new IntersectionObserver((e,t)=>{e.forEach(e=>{if(e.isIntersecting){let o=e.target;o.src=o.dataset.src,o.onload=()=>{o.classList.add("loaded"),o.classList.remove("lazy");let e=o.closest(".post-image");e&&e.classList.remove("loading");let t=o.closest(".post-card");t&&t.classList.add("is-loaded")},t.unobserve(o)}})});e.forEach(e=>t.observe(e))}else e.forEach(e=>{e.src=e.dataset.src,e.classList.remove("lazy")})}

// FITUR DELAY (Untuk Related Posts & Komentar agar tidak menghambat load awal)
function initDeferredFeatures(){let e=document.getElementById("relatedPost"),t=document.getElementById("comment-editor");if("IntersectionObserver"in window){let o=new IntersectionObserver((o,a)=>{o.forEach(o=>{if(o.isIntersecting){o.target===e&&relatedPost(),o.target===t&&postComment(),a.unobserve(o.target)}})},{rootMargin:"300px"});e&&o.observe(e),t&&o.observe(t)}else e&&relatedPost(),t&&setTimeout(postComment,1500)}

// 11. TURBO LOAD EVENT HANDLER
window.onpopstate=function(e){if(e.state&&e.state.tocPos)window.scrollTo({top:e.state.tocPos,behavior:"smooth"});else{var t=document.getElementById("main-toc-area");if(t){var o=t.getBoundingClientRect().top+window.pageYOffset-100;window.scrollTo({top:o,behavior:"smooth"})}}};
document.addEventListener("turbo:load",()=>{scrollHandler&&(window.removeEventListener("scroll",scrollHandler),scrollHandler=null);darkMode();mainNav();adsMove();backToTop();prosesSemuaTagTime();processComments();lazyLoadInit();initTOC();initSmoothZoom();updateAddressBarColor();document.getElementById("postPaginationMultiple")&&postPaginationMultiple();initDeferredFeatures()});
document.addEventListener("turbo:before-visit",function(e){let t=new URL(e.detail.url),o=new URLSearchParams(window.location.search);o.has("m")&&!t.searchParams.has("m")&&(t.searchParams.set("m",o.get("m")),e.preventDefault(),Turbo.visit(t.toString()))});
